[package]
name = "shuttle-rust-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.10.2"
mongodb = "3.2.3"
serde = "1.0.219"
shuttle-actix-web = "0.53.0"
shuttle-runtime = "0.53.0"
